# Generated by Django 5.2.1 on 2025-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название мероприятия, например, Хардатон Инженерный Вызов', verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание мероприятия', verbose_name='Описание')),
                ('date', models.DateField(blank=True, help_text='Дата проведения мероприятия', null=True, verbose_name='Дата')),
                ('media_url', models.URLField(blank=True, help_text='Ссылка на упоминание в соцсетях', verbose_name='СМИ')),
                ('album_url', models.URLField(blank=True, help_text='Ссылка на фотоальбом в соцсетях или на сайте', verbose_name='Альбом')),
                ('on_map_url', models.URLField(blank=True, help_text='Ссылка на место проведения мероприятия в приложение (например, Яндекс Карты)', verbose_name='Место')),
                ('docs_url', models.URLField(blank=True, help_text='Ссылка на нормативные документы, регламентирующие проведение мероприятия', verbose_name='Документы')),
                ('registration_url', models.URLField(blank=True, help_text='Ссылка на регистрацию на событие', verbose_name='Регистрация')),
                ('background_img', models.ImageField(blank=True, help_text='Фоновое изображение для мероприятия', null=True, upload_to='events/backgrounds/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
