# Generated by Django 5.1.7 on 2025-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='background_img',
            field=models.ImageField(blank=True, help_text='Фоновое изображение для мероприятия', null=True, upload_to='events/backgrounds/', verbose_name='Изображение'),
        ),
    ]
