# Generated by Django 5.1.7 on 2025-04-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_event_background_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, help_text='Ссылка на регистрацию на событие', verbose_name='Регистрация'),
        ),
    ]
