# Generated by Django 5.2.1 on 2025-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Заголовок, краткое описание новости', verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, help_text='Текст новости', verbose_name='Содержание')),
                ('href', models.URLField(blank=True, help_text='Ссылка на пост в соцсетях с более подробной информацией', verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, help_text='Изображение для новости', null=True, upload_to='news/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
