# Generated by Django 5.1.7 on 2025-03-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок, краткое описание новости. Не более 100 символов', max_length=100)),
                ('content', models.TextField(help_text='Текст новости')),
                ('href', models.URLField(help_text='Ссылка на пост в соцсетях с более подробной информацией о новости')),
                ('image', models.ImageField(help_text='Изображение для новости', upload_to='news/')),
            ],
        ),
    ]
