# Generated by Django 5.1.7 on 2025-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsrecord',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='content',
            field=models.TextField(help_text='Текст новости', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='href',
            field=models.URLField(help_text='Ссылка на пост в соцсетях с более подробной информацией о новости', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='image',
            field=models.ImageField(help_text='Изображение для новости', upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='title',
            field=models.CharField(help_text='Заголовок, краткое описание новости. Не более 100 символов', max_length=100, verbose_name='Заголовок'),
        ),
    ]
