# Generated by Django 5.1.7 on 2025-03-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок, краткое описание достижения. Не более 100 символов', max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Описание достижения ЦМР', verbose_name='Описание')),
                ('album_url', models.URLField(help_text='Ссылка на фотоальбом в соцсетях или на сайте', verbose_name='Альбом')),
                ('media_url', models.URLField(help_text='Ссылка на упоминание в соцсетях', verbose_name='СМИ')),
                ('image', models.ImageField(help_text='Фотография с мероприятия', null=True, upload_to='achievements', verbose_name='Изображение')),
            ],
        ),
    ]
