# Generated by Django 5.2.1 on 2025-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Заголовок, краткое описание достижения', verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Описание достижения ЦМР', verbose_name='Описание')),
                ('album_url', models.URLField(blank=True, help_text='Ссылка на фотоальбом в соцсетях или на сайте', verbose_name='Альбом')),
                ('media_url', models.URLField(blank=True, help_text='Ссылка на упоминание в соцсетях', verbose_name='СМИ')),
                ('image', models.ImageField(blank=True, help_text='Фотография с мероприятия', null=True, upload_to='achievements/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
    ]
