# Generated by Django 5.1.7 on 2025-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardathonPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField(blank=True, verbose_name='Ссылка')),
                ('title', models.TextField(blank=True, verbose_name='Название')),
                ('photo', models.TextField(blank=True, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Предварительный просмотр хардaтона',
                'verbose_name_plural': 'Предварительные просмотры хардaтонов',
            },
        ),
    ]
