# Generated by Django 5.1.7 on 2025-05-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardathons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardathon',
            name='quote',
            field=models.TextField(blank=True, verbose_name='Цитата'),
        ),
    ]
