# Generated by Django 4.2.6 on 2024-08-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_alter_achievement_link_to_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(help_text='Максимум 220 символов', max_length=220, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='link_to_media',
            field=models.URLField(blank=True, max_length=128, verbose_name='ссылка на СМИ'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='photo_album_url',
            field=models.URLField(blank=True, max_length=128, verbose_name='ссылка на фото-альбом'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(help_text='Максимум 32 символа', max_length=32, verbose_name='название'),
        ),
    ]
