# Generated by Django 4.2.6 on 2024-07-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_alter_achievement_link_to_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='главное достижение'),
        ),
    ]
