# Generated by Django 4.2.6 on 2024-07-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_achievement_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.achievement')),
            ],
        ),
    ]
