# Generated by Django 4.2.6 on 2024-07-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0004_mainachievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainachievement',
            old_name='main_achievement_id',
            new_name='main_achievement',
        ),
    ]
