# Generated by Django 4.2.6 on 2024-07-21 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0006_remove_achievement_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('achievement', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='achievement.achievement')),
            ],
            options={
                'verbose_name': 'порядок достижений',
                'verbose_name_plural': 'порядок достижений',
            },
        ),
        migrations.DeleteModel(
            name='MainAchievement',
        ),
    ]
