# Generated by Django 4.2.6 on 2024-07-21 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def forward_func(apps, schema_editor):
    AchievementOrder = apps.get_model('achievement', 'AchievementOrder')
    db_alias = schema_editor.connection.alias
    AchievementOrder.objects.using(db_alias).bulk_create(
        [
            AchievementOrder(achievement=None, order=1),
            AchievementOrder(achievement=None, order=2),
            AchievementOrder(achievement=None, order=3),
            AchievementOrder(achievement=None, order=4),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0007_achievementorder_delete_mainachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementorder',
            name='achievement',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='achievement.achievement', verbose_name='достижение'),
        ),
        migrations.AlterField(
            model_name='achievementorder',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='порядок'),
        ),
        migrations.RunPython(forward_func),
    ]
