# Generated by Django 4.2.6 on 2024-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardathon', '0002_alter_hardathon_documents_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='competition_rules',
        ),
        migrations.AddField(
            model_name='hardathon',
            name='competition_rules',
            field=models.TextField(default='text', verbose_name='правила соревнования'),
            preserve_default=False,
        ),
    ]
