# Generated by Django 4.2.6 on 2024-08-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardathon', '0003_alter_hardathon_main_organizer_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardathon',
            name='description',
            field=models.TextField(help_text='Максимум 512 символов', max_length=512, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='hardathon',
            name='documents_url',
            field=models.URLField(blank=True, max_length=128, verbose_name='ссылка на документы'),
        ),
        migrations.AlterField(
            model_name='hardathon',
            name='photo_album_url',
            field=models.URLField(blank=True, max_length=128, verbose_name='ссылка на фото-альбом'),
        ),
        migrations.AlterField(
            model_name='hardathon',
            name='title',
            field=models.CharField(help_text='Максимум 32 символа', max_length=32, verbose_name='название'),
        ),
    ]
